package com.alekseyruban.timemanagerapp.analytics_service.service.chronometryAnalytics.model;

public enum IssueParam {
    // LOW_FOCUS
    FOCUS_SCORE,
    FOCUS_LOSS_MINUTES,

    // NO_BREAKS
    TOTAL_BREAKS_MINUTES,
    BREAKS_MINUTES_PER_HOUR,

    // TOO_MANY_TASK_SWITCHES
    TASK_SWITCHES_COUNT,
    TASK_SWITCHES_PER_HOUR,
    AVG_TIME_PER_TASK,

    // EXCESSIVE_MULTITASKING
    MULTITASK_OVERLAP_MINUTES,
    MULTITASK_OVERLAP_MINUTES_PER_HOUR,

    // FRAGMENTED_WORKDAY
    WORK_SESSION_COUNT,
    AVR_SESSION_DURATION,
    AVG_SESSION_GAP,

    // LONG_WORKDAY
    OVERTIME_MINUTES,

    // NO_DAYS_OFF weekly
    TOTAL_WORK_DAYS,
    TOTAL_DAYS_OFF_COUNT,

    // INSUFFICIENT_SLEEP
    SLEEP_DURATION,
    SLEEP_DEFICIT_MINUTES,
    AVG_SLEEP_DURATION, // weekly

    // IRREGULAR_SLEEP weekly
    AVG_SLEEP_START_TIME,
    SLEEP_START_STD_DEV,
    AVG_SLEEP_DURATION_TIME,
    SLEEP_DURATION_STD_DEV,

    // WEEKLY_ISSUE_GENERAL
    WEEKLY_OCCURRENCES,
    MAX_CONSECUTIVE_DAYS,
}